### ISSUE TITLE
Error on start 

### ISSUE THREAD

**Issue by toome123** [Goyapa/mongoduinometeor#1]
Hey , guys ,, i have problem when i start project ... i follow the installation instruction , but when i type "meteor " to start project it's trow this 

```
=> Started proxy.                             
=> A patch (Meteor 1.0.3.2) for your current release is available!
   Update this project now with 'meteor update --patch'.
=> Started MongoDB.                           
npm-container: updating npm dependencies -- johnny-five...
npm ERR! missing: serialport@>=0.7.5, required by firmata@0.3.6
npm ERR! not ok code 0

=> Errors prevented startup:                  

   While building package npm-container:
   error: couldn't read npm version lock information

=> Your application has errors. Waiting for file change.
```

It seems like can't find serial port module , did anyone know how to fix it

**Comment by Goyapa** [comment]
Hi toome123 are u able to run the Johnny-Five Nunchuck sample?

**Comment by ghost** [comment]
Try `npm cache clean` and make sure you have a good internet connection when starting the app.
I just tried starting the app and had no problems.
